apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels: 
    app: mysql
data: 
  primary.cnf: | 
    # Apply only on primary server
    [mysqld]
    log-bin
  replica.cnf: | 
    # Apply this config only on replicas
    [mysqld]
    super-read-only
